train:
  batch_size_per_gpu: 2
  num_workers: 1
  OFFICIAL_EPOCH_LENGTH: 10
  use_wandb: False

optim:
  epochs: 2
  saveckp_freq: 2

eval:
  eval_period_epoch: 10
  eval_period_iterations: -1
  include_final_ckpt: False