
student:
  arch: vit_base
  patch_size: 14
  embed_layer: PatchEmbed
  pretrained_weights: /data/panopticon/other_model_ckpts/dinov2/dinov2_vitb14_pretrain_wmodelkey.pth
  drop_pretrained_weights: 'pos_emb'

val_metrics: # first metric will always be used to determine best classifier
- id: Accuracy
  top_k: 1
  average: micro
- id: Accuracy
  top_k: 1
  average: macro
- id: Accuracy
  top_k: 5
  average: micro


criterion_cfg: 
  id: CrossEntropyLoss

train_dataset:
  id: geobench.m-eurosat
  split: train
  transform:
  - id: Listify
  - id: ListCenterCrop
    size: 56
  - id: ChnSelect
    idxs: [3,2,1]

val_dataset:
  id: geobench.m-eurosat
  split: val
  display_name: m-eurosat
  transform:
  - id: Listify
  - id: ListCenterCrop
    size: 56
  - id: ChnSelect
    idxs: [3,2,1]
  
test_datasets:
  - id: geobench.m-eurosat
    split: test
    display_name: m-eurosat
    transform:
    - id: Listify
    - id: ListCenterCrop
      size: 56
    - id: ChnSelect
      idxs: [3,2,1]

batch_size: 256
num_workers: 4

epochs: 100
epoch_length: 4  # need to choose epoch lenghts manually

save_checkpoint_frequency_epoch: 5
eval_period_iterations: 20