

task:
  id: multilabelclassification
  val_metrics: # first metric will always be used to determine best classifier
  - id: MultiLabelAveragePrecision
    average: macro

    
_vars: # not explicitly used in config, only as variables
  transform: # output is 120x120
  - id: Resize
    size: 112 # divisible by 14

train_dataset:
  id: benv2
  split: train
  root: ${env:RDIR}/datasets/benv2
  bands: s2
  multimodal: false
  subset: 10
  transform: ${_vars.transform}

val_dataset:
  id: benv2
  split: validation
  root: ${env:RDIR}/datasets/benv2
  bands: s2
  multimodal: false
  subset: 10
  transform: ${_vars.transform}

test_datasets_list:
  - id: benv2
    split: test
    root: ${env:RDIR}/datasets/benv2
    bands: s2
    multimodal: false
    subset: 50
    transform: ${_vars.transform}

dl:
  batch_size: 10
  num_workers: 4
  persistent_workers: true

optim:
  epochs: 1 # or max_iter

  save_checkpoint_frequency_epoch: 10
  eval_period_epoch: 1