# vit-B
train:
  batch_size_per_gpu: 50 # max: 55 for big crops, 80 for small crops
  num_workers: 4

eval:
  overwrites:
    optim:
      dl:
        batch_size: 256
        num_workers: 4


# vit-L
# train:
#   batch_size_per_gpu: 22
#   num_workers: 4

# evaluation:
#   dl_cfg:
#     batch_size: 40
#     num_workers: 4