defaults:
  - base_model

model_type: dofa
task: classification
dofa_size: dofa_large
image_resolution: 224
embed_dim: 1024
pretrained_path: "DOFA_ViT_large_e100.pth"
lora: true
lora_target_modules:
 - blocks.22.attn.qkv
 - blocks.22.attn.proj
 - blocks.23.attn.qkv
 - blocks.23.attn.proj

