defaults:
  - model: satmae_seg
  - dataset: geobench_cashew_10band 
  - _self_


# Training parameters
lr: 1e-3
batch_size: 64
num_workers: 10
pin_mem: true
num_gpus: 2
strategy: ddp
epochs: 20
warmup_epochs: 3
seed: 0
output_dir: ./output_dir
task: segmentation
resume: null

