defaults:
  - model: null
  - dataset: null
  - _self_


# Experiment parameters
lr: 1e-3
batch_size: 32
weight_decay: 0.0001
num_workers: 8
pin_mem: true
num_gpus: 1
strategy: null
epochs: 30
warmup_epochs: 0
seed: 0
output_dir: ./output_dir
task: classification
resume: null
size: base