task:
  id: multilabelclassification

  val_metrics:
  - id: MultiLabelAveragePrecision
    average: macro

_vars: # not explicitly used in config, only as variables
  transform: # output is 120x120
  - id: Resize
    size: 224 # divisible by 14

train_dataset:
  id: benv2
  split: train
  root: ${env:RDIR}/datasets/benv2
  bands: all
  multimodal: false
  subset: 0.01
  transform: ${_vars.transform}

val_dataset:
  id: benv2
  split: validation
  root: ${env:RDIR}/datasets/benv2
  bands: all
  multimodal: false
  subset: 0.01
  transform: ${_vars.transform}

test_datasets_list:
- id: benv2
  split: test
  root: ${env:RDIR}/datasets/benv2
  bands: all
  multimodal: false
  subset: 0.01
  transform: ${_vars.transform}

dl:
  batch_size: 512
  num_workers: 12
  persistent_workers: true

optim:
  epochs: 10 # or max_iter

  save_checkpoint_frequency_epoch: 20
  eval_period_epoch: 20