dino:
  loss_weight: 1.0
  koleo_loss_weight: 0.0
ibot:
  loss_weight: 1.0
  separate_head: true
train:
  dataset:
    id: FmowDataset
    split: fmow/metadata_v2/fmow_iwm_onid_train_val_presorted.parquet
    root: /data/panopticon/datasets/
    num_sens: 2
    transform:
    - id: ChnSpatialAugmentation
      global_crops_scale:
      - 0.32
      - 1.0
      local_crops_number: 4
      local_crops_scale:
      - 0.05
      - 0.32
      global_crops_size:
      - 13
      - 196
      local_crops_size:
      - 6
      - 84
      determinisitc_subset: true
  global_smask_absolute_tuple:
  - 13
  - 13
  local_smask_absolute_tuple:
  - 6
  - 6
  batch_size_per_gpu: 140
  num_workers: 12
  drop_last: true
  pin_memory: true
  use_wandb: true
  output_dir: .
  saveckp_freq: 1
  seed: 0
  OFFICIAL_EPOCH_LENGTH: 300
  cache_dataset: true
  centering: centering
  log_every_n_steps: 10
student:
  arch: vit_base
  embed_layer: ChnAttnPatchEmb
  patch_size: 14
  drop_path_rate: 0.0
  layerscale: 1.0e-05
  pretrained_weights: 
  - path: /data/panopticon/other_model_ckpts/dinov2/dinov2_vitb14_pretrain_wmodelkey.pth
    exclude: pos_emb
  ffn_layer: mlp
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 0
  interpolate_antialias: false
  interpolate_offset: 0.1
teacher:
  pretrained_weights: 
  - path: /data/panopticon/other_model_ckpts/dinov2/dinov2_vitb14_pretrain_wmodelkey.pth
    exclude: pos_emb
  momentum_teacher: 0.994
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 30
optim:
  epochs: 8
  weight_decay: 0.04
  weight_decay_end: 0.2
  base_lr: 0.0001
  lr: 5.229125165837973e-05
  warmup_epochs: 0
  min_lr: 1.0e-06
  clip_grad: 3.0
  # freeze_last_layer_epochs: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 2.0
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
evaluation:
  eval_period_epochs: 1
  nb_knn:
  # - 10
  - 20
  # - 50
  train_dataset:
    id: geobench.m-eurosat
    split: train
    transform:
    - id: Listify
    - id: ListCenterCrop
      size: 56
  val_dataset:
    id: geobench.m-eurosat
    split: val
    transform:
    - id: Listify
    - id: ListCenterCrop
      size: 56
  dl_cfg:
    batch_size: 150
    num_workers: 4
    pin_memory: false
  eval_sleep_time: 5
