MODEL:
  pretrained_weights:
  - path: ${env:RDIR}/other_model_ckpts/dinov2/dinov2_vitb14_pretrain.pth
    exclude: pos_emb,patch_embed
    prefix_map: 
      '': teacher.backbone.
  - path: ${env:RDIR}/other_model_ckpts/dinov2/dinov2_vitb14_pretrain.pth
    exclude: pos_emb,patch_embed
    prefix_map: 
      '': student.backbone.
dino:
  loss_weight: 1.0
  koleo_loss_weight: 0.0
ibot:
  loss_weight: 1.0
train:
  dataset:
    id: MMEarth  # nsamples=1'239'937
    base_path: ${env:RDIR}/datasets/mmearth/data_1M_v001
    split: train
    modalities: MODALITY_MINIMAL_SET1

  dino_augm:
    id: ChnSpatialAugmentation
    global_crops_scale: [0.32, 1.0]
    local_crops_number: 4
    local_crops_scale: [0.05, 0.32]
    global_crops_size: [13, 224] # 224
    local_crops_size: [6, 98] # 98

  global_smask_absolute_tuple: [6, 13]
  local_smask_absolute_tuple: [3, 6]

  batch_size_per_gpu: -1
  num_workers: -1
  OFFICIAL_EPOCH_LENGTH: 1250  # 9230 iterations (eff_bsz=2*130) -> 9230/1250=7.384 off epochs = 1 actual epoch

  use_wandb: true
  output_dir: .
  saveckp_freq: 1
  seed: 21
  log_every_n_steps: 10
student:
  arch: vit_base
  embed_layer: ChnAttnPatchEmb
  patch_size: 14
  pos_emb_img_size: 518
  drop_path_rate: 0.0
  layerscale: 1.0e-05
  pe_args:
    chnAttnBlock_cfg:
      id_attn_block: ChnAttnBlockSimple
      norm_input: false
      use_layer_scale: false
      skip_conn: true
      norm_output: false
    chnEmb_cfg:
      n_learnable_embs: 12
teacher:
  momentum_teacher: 0.994
  final_momentum_teacher: 1.0
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 0
optim:
  epochs: 5
  weight_decay: 0.04
  weight_decay_end: 0.2
  base_lr: 0.001
  lr: 0.0
  warmup_epochs: 0
  min_lr: 1.0e-06
  lr_multiplier: backbone=0.2
  freeze_weights: last_layer=1
  scaling_rule: sqrt_wrt_1024,find_lr
  clip_grad: 3.0
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
eval:
  use_online_eval: False
  eval_period_epoch: -1
  eval_period_iterations: 1560 # 4 times (and some buffer)

  config_dir: ${env:CDIR}/eval/offline_train_linear
  remove_ckpts: True
  return_all_results: False
  include_final_ckpt: False
add_args: True