defaults:
  - base_dataset

dataset_type: benv2
task: classification
dataset_name: benv2
num_classes: 19
num_channels: 14
data_path: /mnt/data/datasets_classification/benv2
image_resolution: 224  # Desired image size for model input
band_wavelengths: []
multilabel: true
bands: all  # Argument for torchgeo loader

