defaults:
  - geobench

benchmark_name: segmentation_v1.0
dataset_name: m-cashew-plant
task: segmentation
band_names:
  - "04 - Red"
  - "03 - Green"
  - "02 - Blue"
  - "05 - Vegetation Red Edge"
  - "06 - Vegetation Red Edge"
  - "07 - Vegetation Red Edge"
  - "08 - NIR"
  - "11 - SWIR"
  - "12 - SWIR"
num_classes: 7
multilabel: false
num_channels: 9

