dino:
  loss_weight: 1.0
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.0
ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.5
  separate_head: false
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
train:
  dataset:
    id: FmowDataset
    split: fmow/metadata_v2/fmow_iwm_onid_train_val_presorted.parquet
    root: /data/panopticon/datasets/
    num_sens: 2
    transform:
    - id: ChnSpatialAugmentation
      global_crops_scale:
      - 0.32
      - 1.0
      local_crops_number: 4
      local_crops_scale:
      - 0.05
      - 0.32
      global_crops_size:
      - -1
      - 196
      local_crops_size:
      - -1
      - 84
    return_rgb: true
  global_smask_absolute_tuple: null
  local_smask_absolute_tuple: null
  batch_size_per_gpu: 165
  num_workers: 12
  drop_last: true
  pin_memory: true
  use_wandb: true
  output_dir: /data/panopticon/logs/dino_logs/out/bl_dino_rgb
  saveckp_freq: 1
  seed: 0
  OFFICIAL_EPOCH_LENGTH: 500
  cache_dataset: true
  centering: centering
  log_every_n_steps: 10
student:
  arch: vit_base
  embed_layer: PatchEmbed
  patch_size: 14
  drop_path_rate: 0.0
  layerscale: 1.0e-05
  drop_path_uniform: true
  pretrained_weights: 
  - path: /data/panopticon/other_model_ckpts/dinov2/dinov2_vitb14_pretrain_wmodelkey.pth
    exclude: pos_emb,patch_emb
  ffn_layer: mlp
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 0
  interpolate_antialias: false
  interpolate_offset: 0.1
teacher:
  momentum_teacher: 0.994
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 0
  pretrained_weights: 
  - path: /data/panopticon/other_model_ckpts/dinov2/dinov2_vitb14_pretrain_wmodelkey.pth
    exclude: pos_emb,patch_emb
optim:
  epochs: 50
  weight_decay: 0.04
  weight_decay_end: 0.2
  base_lr: 0.001
  lr: 0.0005676844413932797
  warmup_epochs: 5
  min_lr: 1.0e-06
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.2
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
evaluation:
  eval_period_epochs: 1
  nb_knn:
  - 10
  - 20
  - 50
  train_dataset:
    id: geobench.m-eurosat
    split: train
    transform:
    - id: Listify
    - id: ListCenterCrop
      size: 56
    - id: ChnSelect
      idxs:
      - 3
      - 2
      - 1
  val_dataset:
    id: geobench.m-eurosat
    split: val
    transform:
    - id: Listify
    - id: ListCenterCrop
      size: 56
    - id: ChnSelect
      idxs:
      - 3
      - 2
      - 1
  dl_cfg:
    batch_size: 140
    num_workers: 4
    pin_memory: false
  eval_sleep_time: 5
