# MODEL:
#   pretrained_weights:
#   - path: ${env:RDIR}/other_model_ckpts/dinov2/dinov2_vitb14_pretrain.pth
#     exclude: pos_emb,patch_embed
#     prefix_map: 
#       '': teacher.backbone.
#   - path: ${env:RDIR}/other_model_ckpts/dinov2/dinov2_vitb14_pretrain.pth
#     exclude: pos_emb,patch_embed
#     prefix_map: 
#       '': student.backbone.
dino:
  loss_weight: 1.0
  head_n_prototypes: 10
  head_bottleneck_dim: 128
  head_nlayers: 3
  head_hidden_dim: 256
  koleo_loss_weight: 0.0
ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.5
  separate_head: false
  head_n_prototypes: 10
  head_bottleneck_dim: 128
  head_nlayers: 3
  head_hidden_dim: 256
train:
  dataset:
    id: ConcatDataset
    datasets:
    - id: FmowDataset # nsamples=29955
      root: ${oc.env:RDIR}/datasets/
      split: fmow/metadata_v2/fmow_iwm_onid_train_val_presorted.parquet
      # split: fmow/metadata_v2/fmow_iwm_onid_train_val.parquet
      # min_crop: 42
      # max_crop: 196
      subset: -1
      num_sens: 2
    # - id: MMEarth  # nsamples=1'239'937
    #   base_path: ${env:RDIR}/datasets/mmearth/data_1M_v001
    #   split: train
    #   subset: 200000
    #   modalities: MODALITY_MINIMAL_SET1

  dino_augm:
    id: ChnSpatialAugmentationV2
    global_crops_number: 2
    global_crops_size: 224
    global_crops_scale: [0.32, 1.0]
    local_crops_number: 4
    local_crops_size: 98
    local_crops_scale: [0.05, 0.32]
    global_crops_spectral_size: [6,13]
    local_crops_spectral_size: [3,6]
    global_modes_probs: [0.5, 0.3, 0.2]
    local_modes_probs: [0.2, 0.8]
  
  batch_size_per_gpu: 4
  num_workers: 2

  use_wandb: True
  saveckp_freq: 10
  seed: 0
  OFFICIAL_EPOCH_LENGTH: 1
  cache_dataset: true
  centering: "centering" # or "sinkhorn_knopp"
  log_every_n_steps: 1
student:
  arch: vit_base
  embed_layer: ChnAttnPatchEmb
  patch_size: 14
  pos_emb_img_size: 518
  drop_path_rate: 0.0
  layerscale: 1.0e-05
teacher:
  momentum_teacher: 0.994
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 0
optim:
  epochs: 2
  weight_decay: 0.04
  weight_decay_end: 0.2
  base_lr: 0.001  # learning rate for a batch size of 1024
  lr: 0.  # will be set after applying scaling rule
  warmup_epochs: 0
  min_lr: 1.0e-06
  clip_grad: 3.0
  scaling_rule: sqrt_wrt_1024
  freeze_weights: backbone=2
  lr_multiplier: last_layer=0.2
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999

eval:
  config_dir: ${env:CDIR}/eval/debug2
  remove_ckpts: False
  return_all_results: False
  include_final_ckpt: False
  eval_period_epoch: 1