dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
  loss_weight: 1.0
  koleo_loss_weight: 0.0
ibot:
  separate_head: true
  head_n_prototypes: 131072
  loss_weight: 1.0
train:
  dataset:
    id: FmowDataset
    split: fmow/metadata_v2/fmow_iwm_onid_train_val_presorted.parquet
    root: /data/panopticon/datasets/
    num_sens: 2
    subset: -1
    transform:
    - id: ChnSpatialAugmentation
      global_crops_scale:
      - 0.32
      - 1.0
      local_crops_number: 4
      local_crops_scale:
      - 0.05
      - 0.32
      global_crops_size:
      - 13
      - 196
      local_crops_size:
      - 6
      - 84
      determinisitc_subset: false
  global_smask_absolute_tuple:
  - 6
  - 13
  local_smask_absolute_tuple:
  - 3
  - 6
  batch_size_per_gpu: 24
  num_workers: 12
  use_wandb: false
  output_dir: .
  saveckp_freq: 2
  seed: 0
  OFFICIAL_EPOCH_LENGTH: 10
  cache_dataset: true
  centering: centering
  log_every_n_steps: 1
student:
  arch: vit_large
  patch_size: 14
  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 1
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 0
  layerwise_decay: 1.0

evaluation:
  eval_period_epoch: 10