MODEL:
  pretrained_weights:
  - path: /data/panopticon/other_model_ckpts/dinov2/dinov2_vitb14_pretrain_wmodelkey.pth
    prefix_map: 
      teacher.backbone.: ''
    exclude: pos_emb
  - path: /data/panopticon/other_model_ckpts/dinov2/dinov2_vitb14_pretrain_wmodelkey.pth
    prefix_map: 
      student.backbone.: ''
    exclude: pos_emb
  # - path: /data/panopticon/logs/dino_logs/dino_rgb/bl_dino_rgb/model_final.pth
  #   include: dino_head
dino:
  koleo_loss_weight: 0.0
train:
  dataset:
    id: FmowDataset
    split: fmow/metadata_v2/fmow_iwm_onid_train_val_presorted.parquet
    root: /data/panopticon/datasets/
    num_sens: 2
    transform:
    - id: ChnSpatialAugmentation
      global_crops_scale:
      - 0.32
      - 1.0
      local_crops_number: 4
      local_crops_scale:
      - 0.05
      - 0.32
      global_crops_size: [13,196]
      local_crops_size: [6,84]
      determinisitc_subset: False
  global_smask_absolute_tuple: [6,13]
  local_smask_absolute_tuple: [3,6] 
  
  batch_size_per_gpu: 140
  num_workers: 12

  use_wandb: True
  saveckp_freq: 1
  seed: 0
  OFFICIAL_EPOCH_LENGTH: 270
  centering: "centering" # or "sinkhorn_knopp"
  log_every_n_steps: 10
student:
  arch: vit_base
  embed_layer: ChnAttnPatchEmb
  add_pe_args: 
    id_attn_block: ChnAttnBlockSimple
    norm_input: false
    use_layer_scale: false
    skip_conn: true
    norm_output: false

  patch_size: 14
  drop_path_rate: 0.0
  layerscale: 1.0e-05
teacher:
  momentum_teacher: 0.994
  final_momentum_teacher: 1. # 1.
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07 # 0.07
  warmup_teacher_temp_epochs: 30
optim:
  epochs: 10
  weight_decay: 0.04
  weight_decay_end: 0.2 # 0.2

  base_lr: 0.001  # learning rate for a batch size of 1024
  lr: 0.  # will be set after applying scaling rule
  warmup_epochs: 0
  min_lr: 1.0e-06

  clip_grad: 3.0
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999

  freeze_weights: last_layer=1
  lr_multiplier: backbone=0.2
  scaling_rule: sqrt_wrt_1024,find_lr

evaluation:
  eval_period_epochs: 1
  nb_knn: [20]
  train_dataset:
    id: geobench.m-eurosat
    split: train
    transform:
    - id: Listify
    - id: ListCenterCrop
      size: 56
  val_dataset:
    id: geobench.m-eurosat
    split: val
    transform:
    - id: Listify
    - id: ListCenterCrop
      size: 56
  dl_cfg:
    batch_size: 150
    num_workers: 4 # needs to be >0
    pin_memory: False