MODEL:
  WEIGHTS: ''
dino:
  koleo_loss_weight: 0.0
train:
  dataset:
    id: FmowDataset
    split: fmow/metadata_v2/fmow_iwm_onid_train_val_presorted.parquet
    root: /data/panopticon/datasets/
    num_sens: 2
    transform:
    - id: ChnSpatialAugmentation
      global_crops_scale:
      - 0.32
      - 1.0
      local_crops_number: 4
      local_crops_scale:
      - 0.05
      - 0.32
      global_crops_size: [13,196]
      local_crops_size: [6,84]
  global_smask_absolute_tuple: [6,13]
  local_smask_absolute_tuple: [1,6] 
  
  batch_size_per_gpu: 140
  num_workers: 12

  use_wandb: True
  saveckp_freq: 2
  seed: 0
  OFFICIAL_EPOCH_LENGTH: 300
  cache_dataset: true
  centering: "centering" # or "sinkhorn_knopp"
  log_every_n_steps: 10
student:
  arch: vit_base
  embed_layer: ChnAttnPatchEmb
  patch_size: 14
  drop_path_rate: 0.0
  layerscale: 1.0e-05
  drop_path_uniform: true
  pretrained_weights: '/data/panopticon/other_model_ckpts/dinov2/dinov2_vitb14_pretrain_wmodelkey.pth'
  ffn_layer: "mlp"
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 0
  interpolate_antialias: false
  interpolate_offset: 0.1
teacher:
  pretrained_weights: '/data/panopticon/other_model_ckpts/dinov2/dinov2_vitb14_pretrain_wmodelkey.pth'
  momentum_teacher: 0.994
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 30
optim:
  epochs: 50
  weight_decay: 0.04
  weight_decay_end: 0.2
  base_lr: 0.001  # learning rate for a batch size of 1024
  lr: 0.  # will be set after applying scaling rule
  warmup_epochs: 5
  min_lr: 1.0e-06
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 1.0
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999


evaluation:
  eval_period_epoch: 1
  nb_knn: [10,20,50]
  train_dataset:
    id: geobench.m-eurosat
    split: train
    transform:
    - id: Listify
    - id: ListCenterCrop
      size: 56
  val_dataset:
    id: geobench.m-eurosat
    split: val
    transform:
    - id: Listify
    - id: ListCenterCrop
      size: 56
  dl_cfg:
    batch_size: 150
    num_workers: 4 # needs to be >0
    pin_memory: False